package splitter

import (
	"crypto/sha1"
	"fmt"
	"io"
	"path/filepath"
	"strconv"
	"time"

	"github.com/go-git/go-git/v6/plumbing"
	bolt "go.etcd.io/bbolt"
)

type cache struct {
	key    []byte
	branch string
	db     *bolt.DB
	data   map[string][]byte
}

func newCache(branch string, config *Config) (*cache, error) {
	var err error
	db := config.DB
	if db == nil {
		db, err = bolt.Open(filepath.Join(GitDirectory(config.Path), "splitsh.db"), 0644, &bolt.Options{Timeout: 5 * time.Second})
		if err != nil {
			return nil, err
		}
	}

	c := &cache{
		db:     db,
		branch: branch,
		key:    key(config),
		data:   make(map[string][]byte),
	}

	err = db.Update(func(tx *bolt.Tx) error {
		_, err1 := tx.CreateBucketIfNotExists(c.key)
		return err1
	})
	if err != nil {
		return nil, fmt.Errorf("impossible to create bucket: %s", err)
	}

	return c, nil
}

func (c *cache) close() error {
	err := c.db.Update(func(tx *bolt.Tx) error {
		for k, v := range c.data {
			if err := tx.Bucket(c.key).Put([]byte(k), v); err != nil {
				return err
			}
		}
		return nil
	})
	if err != nil {
		return err
	}

	return c.db.Close()
}

func key(config *Config) []byte {
	h := sha1.New()
	if config.Commit != "" {
		io.WriteString(h, config.Commit)
	} else {
		// value does not matter, should just be always the same
		io.WriteString(h, "oldest")
	}

	io.WriteString(h, strconv.Itoa(config.Git))

	for _, prefix := range config.Prefixes {
		io.WriteString(h, prefix.From)
		io.WriteString(h, prefix.To)
		for _, exclude := range prefix.Excludes {
			io.WriteString(h, exclude)
		}
	}

	return h.Sum(nil)
}

func (c *cache) setHead(head *plumbing.ObjectID) {
	c.data["head/"+c.branch] = head.Bytes()
}

func (c *cache) getHead() *plumbing.ObjectID {
	if head, ok := c.data["head/"+c.branch]; ok {
		// since we set the hash generated by ourself
		// this will always be successful
		hash, _ := plumbing.FromBytes(head)
		return &hash
	}

	var oid *plumbing.ObjectID = nil
	c.db.View(func(tx *bolt.Tx) error {
		result := tx.Bucket(c.key).Get([]byte("head/" + c.branch))
		if result != nil {
			c.data["head/"+c.branch] = result
			hash, _ := plumbing.FromBytes(result)
			oid = &hash
		}
		return nil
	})
	return oid
}

func (c *cache) get(rev *plumbing.ObjectID) *plumbing.ObjectID {
	if v, ok := c.data[string(rev.Bytes())]; ok {
		// since we set the hash generated by ourself
		// this will always be successful
		hash, _ := plumbing.FromBytes(v)
		return &hash
	}

	var oid *plumbing.ObjectID = nil
	c.db.View(func(tx *bolt.Tx) error {
		result := tx.Bucket(c.key).Get(rev.Bytes())
		if result != nil {
			c.data[string(rev.Bytes())] = result
			hash, _ := plumbing.FromBytes(result)
			oid = &hash
		}
		return nil
	})
	return oid
}

func (c *cache) set(rev, newrev *plumbing.ObjectID) {
	c.data[string(rev.Bytes())] = newrev.Bytes()
}

func (c *cache) gets(commits []*plumbing.ObjectID) []*plumbing.ObjectID {
	var oids []*plumbing.ObjectID = nil
	c.db.View(func(tx *bolt.Tx) error {
		b := tx.Bucket(c.key)
		for _, commit := range commits {
			result := c.data[string(commit.Bytes())]
			if result != nil {
				hash, _ := plumbing.FromBytes(result)
				oids = append(oids, &hash)
			} else {
				result := b.Get(commit.Bytes())
				if result != nil {
					hash, _ := plumbing.FromBytes(result)
					oids = append(oids, &hash)
				}
			}
		}
		return nil
	})
	return oids
}

func (c *cache) flush() error {
	return c.db.Update(func(tx *bolt.Tx) error {
		if tx.Bucket(c.key) != nil {
			err := tx.DeleteBucket(c.key)
			if err != nil {
				return err
			}

			_, err = tx.CreateBucketIfNotExists(c.key)
			if err != nil {
				return err
			}
		}

		return nil
	})
}
